version: '3'

services:  
  db:
    image: mongo
    ports: 
      - 27017:27017
  cache:
    image: redis
    ports:
      - 6379:6379
  api:
    environment:
      - SESSION_SECRET_KEY=parangaricutirimiruaro
    image: rafaelbenetti/todo-list
    volumes:
      - ${VOLUME_API}:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - db    
    command: npm install   